{
 "title": "tech measurements",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "timeFunction",
    "label": "Time Function",
    "query": "SHOW MEASUREMENTS WITH MEASUREMENT =~ /^techcatalogue_timer/"
   },
   {
    "name": "rateFunction",
    "label": "Rate Function",
    "query": "SHOW MEASUREMENTS WITH MEASUREMENT =~ /^techcatalogue_count/"
   }
  ]
 },
 "panels": [
  {
   "title": "Operations/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "/^$rateFunction$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "OK vs NotFound responses",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "techcatalogue_count_techcontroller_getsingle_Ok",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "techcatalogue_count_techcontroller_getsingle_NotFound",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Call Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "90th Percentile",
     "measurement": "/^$timeFunction$/",
     "select": [
      [
       { "params": [ "90_percentile" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "95th Percentile",
     "measurement": "/^$timeFunction$/",
     "select": [
      [
       { "params": [ "95_percentile" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "99th Percentile",
     "measurement": "/^$timeFunction$/",
     "select": [
      [
       { "params": [ "99_percentile" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}