{
 "title": "Web Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "timer",
    "label": "Timer",
    "query": "SHOW MEASUREMENTS WITH MEASUREMENT =~ /^web_timer/"
   },
   {
    "name": "count",
    "label": "Count",
    "query": "SHOW MEASUREMENTS WITH MEASUREMENT =~ /^web_count/"
   }
  ]
 },
 "panels": [
  {
   "title": "Timing",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "measurement": "web_timer_homecontroller_getprices",
     "select": [
      [
       { "params": [ "90_percentile" ], "type": "field" }
      ],
      [
       { "params": [ "99_percentile" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "/^$count$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 9, "x": 2, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "web_gauge_homecontroller_registrationqueue",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}