---
apiVersion: v1
kind: ConfigMap
metadata:
  name: influxdb-configmap
  namespace: dev
data:
  influxdb.conf: |-
    [meta]
    dir = "/var/lib/influxdb/meta"

    [data]
    dir = "/var/lib/influxdb/data"
    engine = "tsm1"
    wal-dir = "/var/lib/influxdb/wal"


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-configmap
  namespace: dev
data:
  telegraf.conf: |-
    [[inputs.http_listener]]
      service_address = ":8186"
      read_timeout = "10s"
      write_timeout = "10s"

    [[inputs.statsd]]
      protocol = "udp"
      service_address = ":8125"
      delete_gauges = true
      delete_counters = true
      delete_sets = true
      delete_timings = true
      percentiles = [90, 95, 99]
      percentile_limit = 1000

    [[outputs.file]]
      files = ["stdout", "/tmp/metrics.out"]

    [[outputs.influxdb]]
      urls = ["http://influxdb-service.dev.svc.cluster.local:8086"]
      database = "metrics"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources-configmap
  namespace: dev
data:
  datasource.yml: |-
    apiVersion: 1
    datasources:
    - name: Influxdb
      type: influxdb
      access: proxy
      orgId: 1
      url: http://influxdb-service.dev.svc.cluster.local:8086
      database: metrics
      isDefault: true

